/* ==========================================================================
   AraBuzz — onboard.js
   Getting a grown-up from an invitation to a child who can play.

   The order matters and is deliberate:

     invitation → sign in → your name → what this is (and agree) → a PIN → a child

   The consent screen sits fourth, not first. Nobody should be asked to agree to
   something before they have seen what it is. By the time it appears they have
   read the note, followed the link and typed their name — they know what they
   are agreeing to.

   Every step is one decision on one screen. A parent doing this on a phone,
   standing up, with a child asking for something, should never see two things
   at once.
   ========================================================================== */
(function (w) {
  'use strict';

  const $ = s => document.querySelector(s);
  const esc = s => String(s == null ? '' : s)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

  /* ==========================================================================
     THE CONSENT SCREEN
     Written to be read. Bold lead-in, then one short sentence. If a parent
     reads only the bold parts they still know the six things that matter.
     ========================================================================== */
  const CONSENT = {
    version: '1.0',
    title: 'Before you start',
    intro: [
      `AraBuzz is a small spelling app, made by a parent, for a handful of children
       in the same class. It is not a business.`,
      `Please read this. It is short, and it is written to be read — not to protect
       anybody in court.`
    ],
    what: {
      h: 'What it does',
      p: [
        `It takes the Spell Buzz sheet the school sends each week and turns it into games
         your child will actually play. While they play, it quietly notices which letters
         they keep getting wrong.`,
        `Once a week, it writes that up for you as a short note in plain English — what
         they have got hold of, what is still slippery, and the one or two things worth
         helping with. That note is the main thing AraBuzz gives <b>you</b>; the games are
         what it gives <b>them</b>. There is more about the note further down, because it
         is the part most worth understanding before you agree to any of this.`
      ]
    },
    points: [
      { h: 'The words come from the school’s sheet.',
        p: `We use them exactly as the school wrote them. We never invent a definition or
            look one up ourselves. If the sheet has a mistake in it, AraBuzz repeats that
            mistake — the practice is only ever as good as the sheet.` },
      { h: 'The weekly note is a coach’s observation, not an assessment.',
        p: `It says things like “they spell the ending -tion as -shun”. That is a
            description of what they typed. It is not a psychological test, not a
            diagnosis, and not clinically approved. It cannot tell you whether your child
            has a learning difficulty. If something worries you, please speak to their
            teacher or a professional — not to an app.` },
      { h: 'Your child is never compared with another child.',
        p: `No leaderboards, no rankings, no class averages, ever. Each child’s data is
            kept separately and you see only your own. This is a deliberate decision, not
            an oversight.` },
      { h: 'Who can see your child’s data.',
        p: `You, and Prem, who runs AraBuzz and uploads the weekly sheets. Nobody else.
            Prem can open your child’s view to help fix a problem — and every time he
            does, it is recorded, so there is always a record of who looked and when.` },
      { h: 'What it is never used for.',
        p: `Not sold. Not shared with the school or anyone else. Not used for research.
            Not used to train any AI model. No advertising, and no tracking of you or your
            child across other apps or websites.` },
      { h: 'Where the words go.',
        p: `Practice material and the weekly note are generated by an AI service
            (Anthropic’s API), so your child’s spelling attempts are sent there to
            produce them. Anthropic does not use this to train their models. Everything
            else stays on your device and in a private database.` },
      { h: 'What we collect, which is deliberately very little.',
        p: `Your name, email and mobile. Your child’s first name only, a chosen avatar,
            and their answers to spelling questions. No photographs, no address, no date of
            birth, no school records, no location.` },
      { h: 'Five minutes a day is the whole idea.',
        p: `AraBuzz is built for short, daily practice. More is not better, and nothing in
            it is designed to keep your child on a screen for longer.` }
    ],
    using: {
      h: 'More about that weekly note',
      lead: `This is the part we most want you to read, because a note about your child is
             easy to read as more than it is.`,
      p: [
        `It is written for you, to help you help them — a nudge about what to practise
         next, not a verdict on your child.`,
        `Please don’t lean on it for decisions it isn’t built to carry: choosing a
         school or a stream, arranging tutoring, or anything medical. And please don’t
         pass it on as though it were a formal assessment — it isn’t one, and out of
         context it could easily be read as more than it is.`,
        `Once a note leaves the app we have no way of knowing where it goes or how it is
         read, so we can’t take responsibility for how it is used or interpreted. If
         something in a note worries you, treat it as a good reason to talk to their
         teacher, not as an answer in itself.`
      ]
    },
    first: {
      h: 'The first check',
      p: `Your child starts with a short spelling check so AraBuzz knows where to begin.
          It takes about five minutes. Please treat the first result as a rough sketch
          rather than a verdict — first-day nerves on an unfamiliar app are real, and the
          picture gets more accurate over the following fortnight.`
    },
    leaving: {
      h: 'Changing your mind, and leaving',
      p: `You can withdraw at any time, for any reason, without explaining yourself. There
          are two buttons in your settings: <b>Download everything</b>, which gives you
          your child’s whole record and every note as a file you keep, and
          <b>Delete everything</b>, which removes it from the database permanently. If you
          would rather just ask, message Prem and he will do it and confirm when it is
          done. Withdrawing stops AraBuzz for your child straight away.`
    },
    honest: {
      h: 'The boring but honest bit',
      p: `AraBuzz is provided as it is, with no guarantee that it will be available,
          error-free, or that it will improve your child’s spelling. It is a helpful
          tool made in good faith by a parent, not a professional education service, and it
          is not connected with, endorsed by or affiliated with your child’s school.
          We will only ever email you about AraBuzz itself — the weekly note, and a new
          sheet being ready.`
    },
    agree: 'I have read this. I am this child’s parent or guardian, and I agree.'
  };

  /* ==========================================================================
     Shell
     ========================================================================== */
  let host = null;

  function mount() {
    host = document.getElementById('onboard');
    if (!host) {
      host = document.createElement('div');
      host.id = 'onboard';
      host.className = 'onboard';
      document.body.appendChild(host);
    }
    document.body.classList.add('onboarding');
    return host;
  }

  function close() {
    if (host) host.remove();
    host = null;
    document.body.classList.remove('onboarding');
  }

  function panel(inner, opts) {
    const o = opts || {};
    mount().innerHTML = `
      <div class="ob-wrap ${o.wide ? 'wide' : ''}">
        <div class="ob-brand">
          <img src="assets/icon-192.png" alt="">
          <div>
            <div class="ob-name"><span>Ara</span><span class="gold">Buzz</span></div>
            <div class="ob-tag">${esc(o.tag || 'Spelling practice')}</div>
          </div>
        </div>
        <div class="ob-card">${inner}</div>
        ${o.foot ? `<p class="ob-foot">${o.foot}</p>` : ''}
      </div>`;
    return host;
  }

  const busy = (btn, on, label) => {
    if (!btn) return;
    btn.disabled = on;
    btn.innerHTML = on ? '<span class="loader"></span> ' + (label || 'One moment') : btn.dataset.label;
  };

  function oops(msg) {
    const box = $('#obErr');
    if (box) { box.textContent = msg; box.style.display = 'block'; }
  }

  /* ==========================================================================
     1 · The invitation
     ========================================================================== */
  async function showInvite(code) {
    panel(`<div class="center-text"><span class="loader"></span></div>`);
    let inv = null;
    try { inv = await Cloud.peekInvite(code); } catch (e) { /* handled below */ }

    if (!inv || !inv.valid) {
      return panel(`
        <h1>That invitation isn’t valid</h1>
        <p class="muted">It may have been used already, or it may have expired.
           Ask Prem to send you a new one — it takes him a moment.</p>`);
    }

    panel(`
      <div class="ob-kicker">${esc(inv.invited_by)} invited you</div>
      <h1>AraBuzz</h1>
      <p class="lead">A gamified version of the weekly Spell Buzz sheets, for
         ${esc(inv.family_name)}.</p>
      <ul class="ob-list">
        <li>It starts with a quick five-minute check to see where your child is.</li>
        <li>Then it works out which words and letters they find hard, and practises
            exactly those.</li>
        <li>Points, badges and a garden that grows — they’ll think it’s a game.</li>
        <li>It never makes them feel bad about a wrong answer.</li>
        <li>You get a short note each week on what’s worth helping with.</li>
      </ul>
      <p class="muted small">Just for this class group, and not a commercial app.
         Nobody can see anyone else’s child.</p>

      <div class="field" style="margin-top:20px">
        <label for="obEmail">Your email</label>
        <input id="obEmail" type="email" inputmode="email" autocomplete="email"
               placeholder="you@example.com">
      </div>
      <div id="obErr" class="feedback bad" style="display:none"></div>
      <button class="btn-primary btn-wide" id="obGo" data-label="Send me a link">Send me a link</button>
      <p class="hint center-text">No password to invent. We’ll email you a link that
         signs you in.</p>`,
      { tag: 'You’ve been invited' });

    const go = $('#obGo');
    const send = async () => {
      const email = $('#obEmail').value.trim();
      if (!/^\S+@\S+\.\S+$/.test(email)) return oops('That doesn’t look like an email address.');
      busy(go, true, 'Sending');
      try {
        await Cloud.sendLink(email, location.origin + '?join=' + encodeURIComponent(code));
        sessionStorage.setItem('arabuzz.joining', code);
        checkEmail(email);
      } catch (e) {
        busy(go, false);
        oops(e.message || 'That didn’t send. Try again in a moment.');
      }
    };
    go.onclick = send;
    $('#obEmail').onkeydown = e => { if (e.key === 'Enter') send(); };
  }

  function checkEmail(email) {
    panel(`
      <div class="ob-tick">${window.Icon ? Icon.icon('mail', { size: 40, stroke: 1.4 }) : '✉'}</div>
      <h1>Check your email</h1>
      <p class="lead">We’ve sent a link to <b>${esc(email)}</b>. Tap it and you’re in.</p>
      <p class="muted small">It should arrive within a minute. If it doesn’t, look in
         spam — and if it’s still not there, message Prem.</p>`,
      { tag: 'Almost there' });
  }

  /* ==========================================================================
     2 · Your name
     ========================================================================== */
  function askName(code) {
    panel(`
      <h1>What should we call you?</h1>
      <p class="muted">This is how you’ll appear to Prem, and nowhere else.</p>
      <div class="field"><label for="obName">Your name</label>
        <input id="obName" autocomplete="name" placeholder="Meera Rao"></div>
      <div class="field"><label for="obMob">Mobile <span class="faint">(optional)</span></label>
        <input id="obMob" type="tel" inputmode="tel" autocomplete="tel" placeholder="+91"></div>
      <div id="obErr" class="feedback bad" style="display:none"></div>
      <button class="btn-primary btn-wide" id="obGo" data-label="Continue">Continue</button>`,
      { tag: 'Setting up' });

    const go = $('#obGo');
    go.onclick = async () => {
      const name = $('#obName').value.trim();
      if (name.length < 2) return oops('Please enter your name.');
      busy(go, true);
      try {
        if (code) await Cloud.acceptInvite(code, name, $('#obMob').value.trim());
        else await Cloud.bootstrapAdmin(name);
        sessionStorage.removeItem('arabuzz.joining');
        route();
      } catch (e) {
        busy(go, false);
        oops(e.message || 'Something went wrong.');
      }
    };
  }

  /* ==========================================================================
     3 · What this is, and agreeing to it
     ========================================================================== */
  function askConsent() {
    const C = CONSENT;
    panel(`
      <h1>${esc(C.title)}</h1>
      ${C.intro.map(p => `<p class="lead">${esc(p)}</p>`).join('')}

      <h3 class="ob-h">${esc(C.what.h)}</h3>
      ${C.what.p.map(p => `<p>${p}</p>`).join('')}

      <div class="ob-points">
        ${C.points.map((x, i) => `
          <div class="ob-point">
            <span class="ob-num">${i + 1}</span>
            <div><b>${x.h}</b><p>${x.p}</p></div>
          </div>`).join('')}
      </div>

      <h3 class="ob-h">${esc(C.using.h)}</h3>
      <p class="lead">${esc(C.using.lead)}</p>
      ${C.using.p.map(p => `<p>${p}</p>`).join('')}

      <h3 class="ob-h">${esc(C.first.h)}</h3>
      <p>${C.first.p}</p>

      <h3 class="ob-h">${esc(C.leaving.h)}</h3>
      <p>${C.leaving.p}</p>

      <h3 class="ob-h">${esc(C.honest.h)}</h3>
      <p class="small muted">${C.honest.p}</p>

      <label class="ob-agree" for="obAgree">
        <input type="checkbox" id="obAgree">
        <span>${esc(C.agree)}</span>
      </label>
      <div id="obErr" class="feedback bad" style="display:none"></div>
      <button class="btn-primary btn-wide" id="obGo" data-label="Agree and continue" disabled>
        Agree and continue</button>
      <p class="hint center-text">Version ${esc(C.version)}. We’ll record that you
         agreed, and when.</p>`,
      { wide: true, tag: 'Please read this' });

    const box = $('#obAgree'), go = $('#obGo');
    box.onchange = () => { go.disabled = !box.checked; };
    go.onclick = async () => {
      if (!box.checked) return;
      busy(go, true);
      try {
        const meNow = Cloud.whoAmI();
        await Cloud.recordConsent(meNow && meNow.parent ? meNow.parent.full_name : null);
        route();
      } catch (e) {
        busy(go, false);
        oops(e.message || 'That didn’t save. Try again.');
      }
    };
  }

  /* ==========================================================================
     4 · A PIN, so a nine-year-old can’t read a report about herself
     ========================================================================== */
  function askPin() {
    panel(`
      <h1>Choose a 4-digit PIN</h1>
      <p class="lead">This keeps the grown-ups’ area — the weekly notes and settings —
         out of your child’s hands. It is not your password; it is a lock on a door
         inside the app.</p>
      <div class="field"><label for="obPin">PIN</label>
        <input id="obPin" type="password" inputmode="numeric" autocomplete="new-password"
               maxlength="6" placeholder="••••" class="ob-pin"></div>
      <div class="field"><label for="obPin2">Again, to be sure</label>
        <input id="obPin2" type="password" inputmode="numeric" autocomplete="new-password"
               maxlength="6" placeholder="••••" class="ob-pin"></div>
      <div id="obErr" class="feedback bad" style="display:none"></div>
      <button class="btn-primary btn-wide" id="obGo" data-label="Set my PIN">Set my PIN</button>
      <p class="hint center-text">Four to six digits. Pick something your child won’t
         guess — not their birthday.</p>`,
      { tag: 'Setting up' });

    const go = $('#obGo');
    go.onclick = async () => {
      const a = $('#obPin').value.trim(), b = $('#obPin2').value.trim();
      if (!/^[0-9]{4,6}$/.test(a)) return oops('Four to six digits, numbers only.');
      if (a !== b) return oops('Those two don’t match.');
      busy(go, true);
      try { await Cloud.setPin(a); route(); }
      catch (e) { busy(go, false); oops(e.message || 'That didn’t save.'); }
    };
  }

  /* ==========================================================================
     5 · The child
     ========================================================================== */
  /* Her badge is a plant, drawn by the same hand as the garden she is about to
     grow — so the choice she makes on this screen is already part of the world
     she is joining, rather than a sticker chosen from a sheet. */
  const AVATARS = ['sunflower', 'tomato', 'tulip', 'strawberry', 'chilli', 'lavender', 'lettuce'];

  function askChild() {
    panel(`
      <h1>Who’s going to be playing?</h1>
      <p class="muted">Their first name only — that is all AraBuzz ever stores.</p>
      <div class="field"><label for="obKid">First name</label>
        <input id="obKid" autocomplete="off" placeholder="Kabir"></div>
      <div class="field"><label for="obClass">Class <span class="faint">(optional)</span></label>
        <input id="obClass" placeholder="4B"></div>
      <label class="lbl">Pick a badge</label>
      <div class="ob-avatars" id="obAv">
        ${AVATARS.map((a, i) => `
          <button type="button" data-av="${a}" class="${i === 0 ? 'on' : ''}">
            ${window.Garden ? Garden.sprig({ species: a, box: 6, size: 46, seed: i }) : ''}
            <span>${esc(a)}</span>
          </button>`).join('')}
      </div>
      <div id="obErr" class="feedback bad" style="display:none"></div>
      <button class="btn-primary btn-wide" id="obGo" data-label="That’s them">That’s them</button>
      <p class="hint center-text">You can add another child later.</p>`,
      { tag: 'Nearly done' });

    let avatar = AVATARS[0];
    window.U.$$('#obAv button').forEach(b => b.onclick = () => {
      window.U.$$('#obAv button').forEach(x => x.classList.remove('on'));
      b.classList.add('on'); avatar = b.dataset.av;
    });

    const go = $('#obGo');
    go.onclick = async () => {
      const name = $('#obKid').value.trim();
      if (name.length < 1) return oops('Please enter their first name.');
      busy(go, true);
      try {
        await Cloud.addChild({ name, avatar, classLabel: $('#obClass').value.trim() });
        route();
      } catch (e) {
        busy(go, false);
        oops(/has_consented|row-level/i.test(e.message || '')
          ? 'Please agree to the terms first.'
          : (e.message || 'That didn’t save.'));
      }
    };
  }


  /* ==========================================================================
     6 · Her device, and handing it over
     Two screens most setup flows skip, and both matter more than they look.
     ========================================================================== */

  /** Where will the child actually play? Almost never on the phone the parent
      opened the invitation with. */
  function askDevice() {
    const me = Cloud.whoAmI() || {};
    const kid = (me.children && me.children[0] && me.children[0].name) || 'your child';
    const here = location.origin.replace(/^https?:\/\//, '');
    panel(`
      <h1>Where will ${esc(kid)} be playing?</h1>
      <p class="lead">You are probably reading this on your phone. If ${esc(kid)} will use
         a different device — an iPad, a laptop — set that one up now; it takes a minute.</p>

      <div class="ob-choice" id="obSame">
        <b>On this device</b>
        <span>${esc(kid)} will use this phone or tablet. Nothing more to do.</span>
      </div>
      <div class="ob-choice" id="obOther">
        <b>On another device</b>
        <span>Show me how to set up her iPad or laptop.</span>
      </div>`,
      { tag: 'Nearly there' });

    $('#obSame').onclick = () => handOver();
    $('#obOther').onclick = () => otherDevice(kid, here);
  }

  function otherDevice(kid, here) {
    panel(`
      <h1>Setting up ${esc(kid)}’s device</h1>
      <p class="lead">On the iPad or laptop she will use:</p>
      <ol class="ob-steps">
        <li>Open a browser and go to <b class="ob-addr">${esc(here)}</b></li>
        <li>Enter <b>the same email you just used</b> — that is what links the device to
            your family. A link arrives in your inbox; open it on that device.</li>
        <li>You will land straight in, with ${esc(kid)} already set up. No PIN to redo,
            no details to enter again.</li>
        <li><b>On an iPad, add it to the Home Screen</b> — tap Share, then
            <b>Add to Home Screen</b>. Safari deletes saved data for sites that only ever
            live in a tab, so this step is not optional.</li>
      </ol>
      <p class="hint">You can use as many devices as you like. Her progress follows her,
         because it lives in the account rather than the device.</p>
      <button class="btn-primary btn-wide" id="obGo" data-label="Done — carry on">Done — carry on</button>`,
      { tag: 'Her device' });
    $('#obGo').onclick = () => handOver();
  }

  /** The last screen a grown-up sees. Its whole job is the sentence about not
      helping — a first check that a parent has quietly corrected tells us
      nothing, and then every week after it is aimed at the wrong thing. */
  function handOver() {
    const me = Cloud.whoAmI() || {};
    const kid = (me.children && me.children[0] && me.children[0].name) || 'your child';
    panel(`
      <div class="ob-tick">${window.Icon ? Icon.icon('sparkle', { size: 40, stroke: 1.4 }) : '★'}</div>
      <h1>Now hand it to ${esc(kid)}</h1>
      <p class="lead">She starts with a short spelling check — about twenty words, five
         minutes. It is not marked, and she cannot fail it.</p>

      <div class="ob-warn">
        <b>Please don’t help her with this one.</b>
        <p>Not a hint, not a nudge, not “are you sure?”. It feels unkind for five minutes
           and it is the single most useful thing you can do.</p>
        <p>Everything AraBuzz does afterwards is built on what she can spell
           <em>unaided today</em>. If the first check is a little better than the truth,
           every week that follows practises the wrong words — and she ends up working
           harder for less. Let her get things wrong. That is the point of it.</p>
      </div>

      <p class="muted small">She will never see a score, a red mark, or a comparison with
         anyone else. If she asks how she did, "you showed me exactly what to help you
         with" is both kind and completely true.</p>

      <button class="btn-primary btn-wide" id="obGo" data-label="I’ve handed it over">
        I’ve handed it over</button>`,
      { tag: 'Over to her' });

    $('#obGo').onclick = () => finish();
  }

  function finish() {
    if (location.search) history.replaceState({}, '', location.pathname);
    sessionStorage.removeItem('arabuzz.joining');
    close();
    if (w.UI && UI.afterOnboard) UI.afterOnboard(Cloud.whoAmI());
  }

  /* ==========================================================================
     7 · Signing in when you are already a member
     ========================================================================== */
  function askSignIn() {
    panel(`
      <h1>Welcome back</h1>
      <p class="lead">Enter your email and we’ll send you a link. No password to remember.</p>
      <div class="field"><label for="obEmail">Email</label>
        <input id="obEmail" type="email" inputmode="email" autocomplete="email"
               placeholder="you@example.com"></div>
      <div id="obErr" class="feedback bad" style="display:none"></div>
      <button class="btn-primary btn-wide" id="obGo" data-label="Send me a link">Send me a link</button>`,
      { tag: 'Sign in' });

    const go = $('#obGo');
    const send = async () => {
      const email = $('#obEmail').value.trim();
      if (!/^\S+@\S+\.\S+$/.test(email)) return oops('That doesn’t look like an email address.');
      busy(go, true, 'Sending');
      try { await Cloud.sendLink(email, location.origin); checkEmail(email); }
      catch (e) { busy(go, false); oops(e.message || 'That didn’t send.'); }
    };
    go.onclick = send;
    $('#obEmail').onkeydown = e => { if (e.key === 'Enter') send(); };
  }

  /* ==========================================================================
     The router: what does this person need next?
     ========================================================================== */
  function inviteCode() {
    const q = new URLSearchParams(location.search).get('join');
    return q || sessionStorage.getItem('arabuzz.joining') || null;
  }

  async function route() {
    const code = inviteCode();

    if (!Cloud.signedIn()) {
      if (code) return showInvite(code);
      return askSignIn();
    }

    const me = Cloud.whoAmI() || await Cloud.load();

    if (!me || !me.parent)   return askName(code);      // signed in, not yet joined
    if (!me.hasConsented)    return askConsent();
    if (!Cloud.pinIsSet())   return askPin();

    if (!me.isAdmin) {
      if (!me.children.length) return askChild();
      // Only the first time: which device, then the hand-over.
      if (!localStorage.getItem('arabuzz.handedOver')) {
        localStorage.setItem('arabuzz.handedOver', '1');
        return askDevice();
      }
    }

    finish();
  }

  /** True when the app should stay out of the way until setup is finished. */
  function needed() {
    if (!Cloud.available()) return false;
    if (inviteCode()) return true;
    if (!Cloud.signedIn()) return true;
    const me = Cloud.whoAmI();
    if (!me) return true;
    if (!me.parent || !me.hasConsented || !Cloud.pinIsSet()) return true;
    if (!me.isAdmin && !me.children.length) return true;
    return false;
  }

  w.Onboard = { route, needed, close, CONSENT, askSignIn, askConsent, askPin, askChild,
                askDevice, handOver };
})(window);
