/* ==========================================================================
   AraBuzz — onboard.js
   Getting a grown-up from an invitation to a child who can play.

   The order matters and is deliberate:

     invitation → sign in → your name → what this is (and agree) → a PIN → a child

   The consent screen sits fourth, not first. Nobody should be asked to agree to
   something before they have seen what it is. By the time it appears they have
   read the note, followed the link and typed their name — they know what they
   are agreeing to.

   Every step is one decision on one screen. A parent doing this on a phone,
   standing up, with a child asking for something, should never see two things
   at once.
   ========================================================================== */
(function (w) {
  'use strict';

  const $ = s => document.querySelector(s);
  const esc = s => String(s == null ? '' : s)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

  /* ==========================================================================
     THE CONSENT SCREEN
     Written to be read. Bold lead-in, then one short sentence. If a parent
     reads only the bold parts they still know the six things that matter.
     ========================================================================== */
  const CONSENT = {
    version: '1.1',
    title: 'Before you start',
    intro: [
      `AraBuzz is a small spelling app, made by a parent, for a handful of children
       in the same class. It is not a business.`,
      `Please read this. It is short, and it is written to be read — not to protect
       anybody in court.`
    ],
    what: {
      h: 'What it does',
      p: [
        `It takes the Spell Buzz sheet the school sends each week and turns it into
         <b>game-based learning exercises</b>. To your child it feels like playing —
         points, badges, a garden that grows. What they are actually doing, round after
         round, is practising their spellings.`,
        `Each new sheet begins as a <b>learning module</b>: your child meets the words
         first — sees them, hears them, learns what they mean — with nothing marked and
         nothing to get wrong. Only then do the games and practice exercises begin,
         built from those same words. While they play, AraBuzz quietly notices which
         letters keep going wrong.`,
        `Once a week, it writes that up for you as a short note. The note has its own
         section below, because it is the part most worth understanding before you
         agree to any of this.`
      ]
    },
    points: [
      { h: 'The words come from the school’s sheet.',
        p: `We use them exactly as the school wrote them. We never invent a definition or
            look one up ourselves. If the sheet has a mistake in it, AraBuzz repeats that
            mistake — the practice is only ever as good as the sheet.` },
      { h: 'Your child is never compared with another child.',
        p: `No leaderboards, no rankings, no class averages, ever. Each child’s data is
            kept separately and you see only your own. This is a deliberate decision, not
            an oversight.` },
      { h: 'Who can see your child’s data.',
        p: `You, and Prem, who runs AraBuzz and uploads the weekly sheets. Nobody else.
            If something goes wrong technically, Prem can open your child’s view to fix
            it — and every time he does, it is recorded, so there is always a record of
            who looked and when.` },
      { h: 'What it is never used for.',
        p: `Not sold. Not shared with the school or anyone else. Not used for research.
            Not used to train any AI model. No advertising, and no tracking of you or your
            child across other apps or websites.` },
      { h: 'Where the words go.',
        p: `Practice material and the weekly note are generated by an AI service
            (Anthropic’s API), so your child’s spelling attempts are sent there to
            produce them. Anthropic does not use this to train their models. Everything
            else stays on your device and in a private database.` },
      { h: 'What we collect, which is deliberately very little.',
        p: `Your name, email and mobile. Your child’s first name only, a chosen avatar,
            and their answers to spelling questions. No photographs, no address, no date of
            birth, no school records, no location.` },
      { h: 'About twenty minutes a day is the sweet spot.',
        p: `AraBuzz works best as short, focused daily practice — around twenty minutes is
            ideal. More than that earns nothing extra, and nothing in the app is designed
            to keep your child on a screen for longer.` }
    ],
    note: {
      h: 'The weekly note',
      lead: `Once a week, AraBuzz writes you a short note about your child’s spelling.
             This is the part we most want you to read.`,
      is: {
        h: 'What it is',
        p: [
          `A few plain-English paragraphs from the week’s practice: what your child has
           got hold of, what is still tricky, and one or two specific things worth
           helping with — with their own spellings quoted as evidence, things like
           “they wrote ‘becuase’ three times this week”.`,
          `Think of it as an observation sheet from a coach who watched every round.
           It is written for you, to help you help them — a nudge about what to practise
           next, never a verdict on your child.`
        ]
      },
      isnt: {
        h: 'What it is not',
        p: [
          `It is not a clinical report, not a diagnosis, and not a formal assessment —
           that is exactly why we call it a <b>note</b> and not a report. It cannot tell
           you whether your child has a learning difficulty.`,
          `Please don’t use it for decision-making — choosing a school, arranging
           tutoring, or anything medical — and please don’t pass it on as if it were a
           formal assessment. If something in a note worries you, treat it as a good
           reason to talk to their teacher, not as an answer in itself.`
        ]
      }
    },
    first: {
      h: 'The first check',
      p: `Your child starts with a short spelling check so AraBuzz knows where to begin.
          It takes about five minutes. Please treat the first result as a rough sketch
          rather than a verdict — first-day nerves on an unfamiliar app are real, and the
          picture gets more accurate over the following fortnight.`
    },
    leaving: {
      h: 'Changing your mind, and leaving',
      p: `You can withdraw at any time, for any reason, without explaining yourself. There
          are two buttons in your settings: <b>Download everything</b>, which gives you
          your child’s whole record and every note as a file you keep, and
          <b>Delete everything</b>, which removes it from the database permanently. If you
          would rather just ask, message Prem and he will do it and confirm when it is
          done. Withdrawing stops AraBuzz for your child straight away.`
    },
    honest: {
      h: 'The boring but honest bit',
      p: `AraBuzz is provided as it is, with no guarantee that it will be available,
          error-free, or that it will improve your child’s spelling. It is a helpful
          tool made in good faith by a parent, not a professional education service, and it
          is not connected with, endorsed by or affiliated with your child’s school.
          We will only ever email you about AraBuzz itself — the weekly note, and a new
          sheet being ready.`
    },
    agree: 'I have read this. I am this child’s parent or guardian, and I agree.'
  };

  /* ==========================================================================
     Shell
     ========================================================================== */
  let host = null;

  function mount() {
    host = document.getElementById('onboard');
    if (!host) {
      host = document.createElement('div');
      host.id = 'onboard';
      host.className = 'onboard';
      document.body.appendChild(host);
    }
    document.body.classList.add('onboarding');
    return host;
  }

  function close() {
    if (host) host.remove();
    host = null;
    document.body.classList.remove('onboarding');
  }

  function panel(inner, opts) {
    const o = opts || {};
    mount().innerHTML = `
      <div class="ob-wrap ${o.wide ? 'wide' : ''}">
        <div class="ob-brand">
          <img src="assets/icon-192.png" alt="">
          <div>
            <div class="ob-name"><span>Ara</span><span class="gold">Buzz</span></div>
            <div class="ob-tag">${esc(o.tag || 'Spelling practice')}</div>
          </div>
        </div>
        <div class="ob-card">${inner}</div>
        ${o.foot ? `<p class="ob-foot">${o.foot}</p>` : ''}
      </div>`;
    /* Enter should always mean "carry on". Every onboarding card has one
       obvious primary button; pressing Enter in any of its fields clicks it. */
    const primary = host.querySelector('.btn-primary, .btn-go');
    if (primary) host.querySelectorAll('input').forEach(inp => {
      inp.addEventListener('keydown', e => {
        if (e.key === 'Enter' && !primary.disabled) { e.preventDefault(); primary.click(); }
      });
    });
    return host;
  }

  const busy = (btn, on, label) => {
    if (!btn) return;
    btn.disabled = on;
    btn.innerHTML = on ? '<span class="loader"></span> ' + (label || 'One moment') : btn.dataset.label;
  };

  function oops(msg) {
    const box = $('#obErr');
    if (box) { box.textContent = msg; box.style.display = 'block'; }
  }

  /* ==========================================================================
     1 · The invitation
     ========================================================================== */
  async function showInvite(code) {
    panel(`<div class="center-text"><span class="loader"></span></div>`);
    let inv = null;
    try { inv = await Cloud.peekInvite(code); } catch (e) { /* handled below */ }

    if (!inv || !inv.valid) {
      return panel(`
        <h1>That invitation isn’t valid</h1>
        <p class="muted">It may have been used already, or it may have expired.
           Ask Prem to send you a new one — it takes him a moment.</p>`);
    }

    // remember who this invitation greeted, for the "Do I call you…?" screen
    sessionStorage.setItem('arabuzz.invname', inv.family_name || '');

    panel(`
      <div class="ob-kicker">${esc(inv.invited_by)} invited you</div>
      <h1>Hi ${esc(inv.family_name)}</h1>
      <p class="lead">AraBuzz turns the weekly Spell Buzz sheets shared by the school into
         game-based practice — it feels like playing, but it's really spelling training.</p>
      <ul class="ob-list">
        <li>It starts with a quick five-minute check to see where your child is.</li>
        <li>Then it works out which words and letters they find hard, and practises
            exactly those.</li>
        <li>Points, badges and a garden that grows — they’ll think it’s a game.</li>
        <li>It never makes them feel bad about a wrong answer.</li>
        <li>You get a short note each week on what’s worth helping with.</li>
      </ul>
      <p class="muted small">It’s not a business — Prem made it for his own kids and is
         sharing it only with close friends. Nobody can see anyone else’s child, and you
         can delete your data and leave at any time.</p>

      <div class="field" style="margin-top:20px">
        <label for="obEmail">Enter your email address to register your account</label>
        <input id="obEmail" type="email" inputmode="email" autocomplete="email"
               placeholder="you@example.com">
      </div>
      <div id="obErr" class="feedback bad" style="display:none"></div>
      <button class="btn-primary btn-wide" id="obGo" data-label="Email me a sign-in code">
        Email me a sign-in code</button>
      <p class="hint center-text">You’ll confirm it by typing the code we send there —
         so make sure it’s an email you actively check. No password to invent.</p>`,
      { tag: 'You’ve been invited' });

    const go = $('#obGo');
    const send = async () => {
      const email = $('#obEmail').value.trim();
      if (!/^\S+@\S+\.\S+$/.test(email)) return oops('That doesn’t look like an email address.');
      // The invitation is addressed. A different email typed here would only
      // fail later at the join, so say it now, kindly.
      if (inv && inv.email && email.toLowerCase() !== String(inv.email).trim().toLowerCase()) {
        return oops('This invitation was sent to ' + inv.email + ' — please use that address. ' +
                    'If you’d rather use a different one, ask Prem to send a fresh invitation there.');
      }
      busy(go, true, 'Sending');
      try {
        await Cloud.sendLink(email, location.origin + '?join=' + encodeURIComponent(code));
        sessionStorage.setItem('arabuzz.joining', code);
        askCode(email, () => showInvite(code));
      } catch (e) {
        busy(go, false);
        oops(e.message || 'That didn’t send. Try again in a moment.');
      }
    };
    go.onclick = send;
    $('#obEmail').onkeydown = e => { if (e.key === 'Enter') send(); };
  }

  /* ==========================================================================
     The six-digit code
     The email carries a code AND a link; both work. The code matters for the
     everyday case — the email opens on the parent's phone, but AraBuzz is
     sitting open on the child's iPad. Reading six digits across the room
     beats forwarding a link.
     ========================================================================== */
  function askCode(email, back) {
    panel(`
      <div class="ob-tick">${window.Icon ? Icon.icon('mail', { size: 40, stroke: 1.4 }) : '✉'}</div>
      <h1>Check your email</h1>
      <p class="lead">We’ve sent a sign-in code to <b>${esc(email)}</b>.</p>
      <div class="field"><label for="obCode">Type the code here</label>
        <input id="obCode" inputmode="numeric" autocomplete="one-time-code" maxlength="10"
               placeholder="12345678" class="ob-pin" style="letter-spacing:.3em;text-align:center;font-size:1.4rem">
      </div>
      <div id="obErr" class="feedback bad" style="display:none"></div>
      <button class="btn-primary btn-wide" id="obGo" data-label="Sign me in">Sign me in</button>
      <p class="hint center-text">The email also has a link — tapping that works too.
         Nothing in a minute? Check spam, or <a href="#" id="obAgain">send another code</a>.</p>
      <button class="btn-quiet btn-wide" id="obBackBtn" style="margin-top:10px">← Back</button>`,
      { tag: 'Almost there' });
    $('#obBackBtn').onclick = () => (back || askSignIn)();

    const go = $('#obGo');
    const verify = async () => {
      const codeTyped = $('#obCode').value.replace(/\D/g, '');
      if (codeTyped.length < 6) return oops('Type the whole code from the email.');
      busy(go, true, 'Checking');
      try {
        await Cloud.verifyCode(email, codeTyped);
        route();
      } catch (e) {
        busy(go, false);
        oops(/expired|invalid/i.test(e.message || '') ?
          'That code didn’t match. Codes only last a little while — send a fresh one if in doubt.'
          : (e.message || 'That didn’t work. Try again.'));
      }
    };
    go.onclick = verify;
    $('#obCode').onkeydown = e => { if (e.key === 'Enter') verify(); };
    $('#obAgain').onclick = async (e) => {
      e.preventDefault();
      try {
        const codeStored = sessionStorage.getItem('arabuzz.joining');
        await Cloud.sendLink(email, codeStored
          ? location.origin + '?join=' + encodeURIComponent(codeStored) : location.origin);
        window.U.toast('A fresh code is on its way.', 'good');
      } catch (err) { oops(err.message || 'Could not resend.'); }
    };
  }

  /* ==========================================================================
     2 · Your name
     The invitation already knows what Prem calls this person, so the screen
     confirms rather than asks. One tap for almost everyone; a box for the
     person Prem knows as "Chikki" who would rather sign up as Lakshmi.
     ========================================================================== */
  async function askName(code) {
    let invited = (sessionStorage.getItem('arabuzz.invname') || '').trim();

    /* The email-code sign-in often lands in a fresh tab, where sessionStorage
       is empty — so ask the invitation itself rather than trusting a note
       that may not have survived the journey. */
    if (!invited && code) {
      try {
        const inv = await Cloud.peekInvite(code);
        if (inv && inv.family_name) invited = String(inv.family_name).trim();
      } catch (e) { /* fine — the plain question below still works */ }
    }

    if (invited) {
      panel(`
        <h1>Do I call you ${esc(invited)}?</h1>
        <p class="muted">That’s the name on your invitation — change it below if you’d like.</p>
        <p class="muted small">This is <b>your</b> grown-up profile, not your kid’s.
           Your kid introduces themself to Ara later, on their own device.</p>
        <button class="btn-primary btn-wide" id="obYes" data-label="Yes — I’m ${esc(invited)}">
          Yes — I’m ${esc(invited)}</button>
        <div class="field" style="margin-top:18px">
          <label for="obName">Or something else</label>
          <input id="obName" autocomplete="name" placeholder="The name you'd prefer"></div>
        <div class="field"><label for="obMob">Mobile <span class="faint">(optional)</span></label>
          <input id="obMob" type="tel" inputmode="tel" autocomplete="tel" placeholder="+91"></div>
        <div id="obErr" class="feedback bad" style="display:none"></div>
        <button class="btn-quiet btn-wide" id="obGo" data-label="Use that name instead">Use that name instead</button>`,
        { tag: 'Nice to meet you' });

      const join = async (name, btn) => {
        busy(btn, true);
        try {
          await Cloud.acceptInvite(code, name, $('#obMob').value.trim());
          if (sessionStorage.getItem('arabuzz.preagreed')) {
            try { await Cloud.recordConsent(name); } catch (e) { console.warn('consent retried later', e); }
            sessionStorage.removeItem('arabuzz.preagreed');
          }
          sessionStorage.removeItem('arabuzz.joining');
          sessionStorage.removeItem('arabuzz.invname');
          route();
        } catch (e) { busy(btn, false); oops(e.message || 'Something went wrong.'); }
      };
      $('#obYes').onclick = () => join(invited, $('#obYes'));
      $('#obName').oninput = () => {
        // typing a different name makes "use that instead" the obvious button
        $('#obGo').classList.toggle('btn-primary', !!$('#obName').value.trim());
      };
      $('#obGo').onclick = () => {
        const alt = $('#obName').value.trim();
        if (alt.length < 2) return oops('Type the name you’d prefer first.');
        join(alt, $('#obGo'));
      };
      return;
    }

    panel(`
      <h1>What should we call you?</h1>
      <p class="muted small">Your own name — this is <b>your</b> grown-up profile, not your
         kid’s. Your kid introduces themself to Ara later.</p>
      <div class="field"><label for="obName">Your name</label>
        <input id="obName" autocomplete="name" placeholder="Meera"></div>
      <div class="field"><label for="obMob">Mobile <span class="faint">(optional)</span></label>
        <input id="obMob" type="tel" inputmode="tel" autocomplete="tel" placeholder="+91"></div>
      <div id="obErr" class="feedback bad" style="display:none"></div>
      <button class="btn-primary btn-wide" id="obGo" data-label="Continue">Continue</button>`,
      { tag: 'Setting up' });

    const go = $('#obGo');
    go.onclick = async () => {
      const name = $('#obName').value.trim();
      if (name.length < 2) return oops('Please enter your name.');
      busy(go, true);
      try {
        if (code) await Cloud.acceptInvite(code, name, $('#obMob').value.trim());
        else await Cloud.bootstrapAdmin(name);
        if (sessionStorage.getItem('arabuzz.preagreed')) {
          try { await Cloud.recordConsent(name); } catch (e2) { console.warn('consent retried later', e2); }
          sessionStorage.removeItem('arabuzz.preagreed');
        }
        sessionStorage.removeItem('arabuzz.joining');
        route();
      } catch (e) {
        busy(go, false);
        oops(e.message || 'Something went wrong.');
      }
    };
  }

  /* ==========================================================================
     3 · What this is, and agreeing to it
     ========================================================================== */
  function askConsent(beforeJoining) {
    const C = CONSENT;
    panel(`
      <h1>${esc(C.title)}</h1>
      ${C.intro.map(p => `<p class="lead">${esc(p)}</p>`).join('')}

      <h3 class="ob-h">${esc(C.what.h)}</h3>
      ${C.what.p.map(p => `<p>${p}</p>`).join('')}

      <div class="ob-points">
        ${C.points.map((x, i) => `
          <div class="ob-point">
            <span class="ob-num">${i + 1}</span>
            <div><b>${x.h}</b><p>${x.p}</p></div>
          </div>`).join('')}
      </div>

      <h3 class="ob-h">${esc(C.note.h)}</h3>
      <p class="lead">${esc(C.note.lead)}</p>
      <p style="margin-bottom:6px"><b>${esc(C.note.is.h)}</b></p>
      ${C.note.is.p.map(p => `<p>${p}</p>`).join('')}
      <p style="margin-bottom:6px"><b>${esc(C.note.isnt.h)}</b></p>
      ${C.note.isnt.p.map(p => `<p>${p}</p>`).join('')}

      <h3 class="ob-h">${esc(C.first.h)}</h3>
      <p>${C.first.p}</p>

      <h3 class="ob-h">${esc(C.leaving.h)}</h3>
      <p>${C.leaving.p}</p>

      <h3 class="ob-h">${esc(C.honest.h)}</h3>
      <p class="small muted">${C.honest.p}</p>

      <label class="ob-agree" for="obAgree">
        <input type="checkbox" id="obAgree">
        <span>${esc(C.agree)}</span>
      </label>
      <div id="obErr" class="feedback bad" style="display:none"></div>
      <button class="btn-primary btn-wide" id="obGo" data-label="Agree and continue" disabled>
        Agree and continue</button>
      <p class="hint center-text">Version ${esc(C.version)}. We’ll record that you
         agreed, and when.</p>`,
      { wide: true, tag: 'Please read this' });

    const box = $('#obAgree'), go = $('#obGo');
    box.onchange = () => { go.disabled = !box.checked; };
    go.onclick = async () => {
      if (!box.checked) return;
      busy(go, true);
      if (beforeJoining) {
        // Their account doesn't exist yet — remember the agreement and write it
        // to the record the moment it does (see askName).
        sessionStorage.setItem('arabuzz.preagreed', '1');
        return route();
      }
      try {
        const meNow = Cloud.whoAmI();
        await Cloud.recordConsent(meNow && meNow.parent ? meNow.parent.full_name : null);
        route();
      } catch (e) {
        busy(go, false);
        oops(e.message || 'That didn’t save. Try again.');
      }
    };
  }

  /* ==========================================================================
     4 · A PIN, so a nine-year-old can’t read a report about herself
     ========================================================================== */
  function askPin() {
    panel(`
      <h1>Choose a 4-digit PIN</h1>
      <p class="lead">This keeps the grown-ups’ area — the weekly notes and settings —
         out of your child’s hands. It is not your password; it is a lock on a door
         inside the app.</p>
      <div class="field"><label for="obPin">PIN</label>
        <input id="obPin" type="password" inputmode="numeric" autocomplete="new-password"
               maxlength="6" placeholder="••••••" class="ob-pin"></div>
      <div class="field"><label for="obPin2">Again, to be sure</label>
        <input id="obPin2" type="password" inputmode="numeric" autocomplete="new-password"
               maxlength="6" placeholder="••••••" class="ob-pin"></div>
      <div id="obErr" class="feedback bad" style="display:none"></div>
      <button class="btn-primary btn-wide" id="obGo" data-label="Set my PIN">Set my PIN</button>
      <p class="hint center-text">Four to six digits. Pick something your child won’t
         guess — not their birthday.</p>`,
      { tag: 'Setting up' });

    const go = $('#obGo');
    go.onclick = async () => {
      const a = $('#obPin').value.trim(), b = $('#obPin2').value.trim();
      if (!/^[0-9]{4,6}$/.test(a)) return oops('Four to six digits, numbers only.');
      if (a !== b) return oops('Those two don’t match.');
      busy(go, true);
      try { await Cloud.setPin(a); route(); }
      catch (e) { busy(go, false); oops(e.message || 'That didn’t save.'); }
    };
  }

  /* ==========================================================================
     5 · There is deliberately NO "add your child" screen here.
     The parent finishes their part — agreeing, and a PIN — and hands the
     device over. The child types their own name, to Ara, on the next screen.
     A nine-year-old introducing themself to a macaw is a better first minute
     than being registered by a grown-up.
     ========================================================================== */


  /* ==========================================================================
     6 · Her device, and handing it over
     Two screens most setup flows skip, and both matter more than they look.
     ========================================================================== */

  /** Where will the child actually play? Almost never on the phone the parent
      opened the invitation with. */
  /** The child this whole flow has been about, and the words to describe them. */
  function theChild() {
    const me = Cloud.whoAmI() || {};
    const kid = (me.children && me.children[0]) || null;
    return {
      name: (kid && kid.name) || 'your child',
      p: window.U.pronouns(kid ? kid.pronoun : 'they')
    };
  }

  function askDevice() {
    const { name: kid, p } = theChild();   // 'your child' + they, until the child names themself
    const here = ((window.CONFIG && CONFIG.APP_URL) || location.origin).replace(/^https?:\/\//, '');
    panel(`
      <h1>Where will ${esc(kid)} be playing?</h1>
      <p class="lead">You are probably reading this on your phone. If ${esc(kid)} will use
         a different device — an iPad, a laptop — set that one up now; it takes a minute.</p>

      <div class="ob-choice" id="obSame">
        <b>On this device</b>
        <span>${esc(kid)} will use this phone or tablet. Nothing more to do.</span>
      </div>
      <div class="ob-choice" id="obOther">
        <b>On another device</b>
        <span>Show me how to set up ${p.their()} iPad or laptop.</span>
      </div>`,
      { tag: 'Nearly there' });

    $('#obSame').onclick = () => handOver();
    $('#obOther').onclick = () => otherDevice(kid, here, p);
  }

  function otherDevice(kid, here, p) {
    panel(`
      <h1>Setting up ${esc(kid)}’s device</h1>
      <p class="lead">On the iPad or laptop ${p.they()} will use:</p>
      <ol class="ob-steps">
        <li>Open a browser and go to <b class="ob-addr">${esc(here)}</b></li>
        <li>Choose <b>sign in</b> and enter <b>the same email you just used</b> — that is
            what links the device to your family.</li>
        <li>A <b>6-digit code</b> lands in your email. Read it on this phone, and
            <b>type it into the iPad or laptop</b>. That device is now yours — nothing
            needs to arrive on it.</li>
        <li>It lands straight in, with ${esc(kid)} already set up. No PIN to redo,
            no details to enter again.</li>
        <li><b>Install it as an app on that device</b> — one tap to open every time,
            and the saved words stay safe.
            <a href="#" id="obInstallHow"><b>How to install it \u2192</b></a></li>
      </ol>
      <p class="hint">You can use as many devices as you like. ${p.Cap.their()} progress
         follows ${p.them()}, because it lives in the account rather than the device.</p>
      <button class="btn-primary btn-wide" id="obGo" data-label="Done — carry on">Done — carry on</button>
      <button class="btn-quiet btn-wide" id="obBack" style="margin-top:10px">← Back</button>`,
      { tag: 'Another device' });
    $('#obGo').onclick = () => handOver();
    $('#obBack').onclick = () => askDevice();
    $('#obInstallHow').onclick = (e) => { e.preventDefault(); installGuide(() => otherDevice(kid, here, p)); };
  }

  /** How to put AraBuzz on the home screen, browser by browser. Reached from
   *  the hand-over and other-device screens; `backTo` returns the parent to
   *  exactly where they were. Where the browser offers a REAL install prompt
   *  (Chrome, Edge), a one-tap Install button appears above the steps. */
  function installGuide(backTo) {
    const here = ((window.CONFIG && CONFIG.APP_URL) || location.origin).replace(/^https?:\/\//, '');
    const canPrompt = !!window.ARABUZZ_INSTALL;
    const B = [
      ['iPhone & iPad — Safari', [
        `Open <b>${esc(here)}</b> in <b>Safari</b> (it has to be Safari).`,
        `Tap the <b>Share</b> button — the square with the arrow.`,
        `Scroll down and tap <b>Add to Home Screen</b>, then <b>Add</b>.`
      ]],
      ['Android — Chrome', [
        `Open <b>${esc(here)}</b> in Chrome.`,
        `Tap the <b>⋮</b> menu at the top right.`,
        `Tap <b>Add to Home screen</b> (or <b>Install app</b>), then <b>Install</b>.`
      ]],
      ['Android — Samsung Internet', [
        `Open <b>${esc(here)}</b>.`,
        `Tap the <b>≡</b> menu, then <b>Add page to</b>.`,
        `Choose <b>Home screen</b>, then <b>Add</b>.`
      ]],
      ['Computer — Chrome', [
        `Open <b>${esc(here)}</b>.`,
        `Click the small <b>install icon</b> at the right end of the address bar
         (a screen with a down arrow), then <b>Install</b>.`,
        `No icon? Menu <b>⋮</b> → <b>Cast, save and share</b> → <b>Install page as app</b>.`
      ]],
      ['Computer — Edge', [
        `Open <b>${esc(here)}</b>.`,
        `Menu <b>…</b> at the top right → <b>Apps</b> → <b>Install this site as an app</b>.`
      ]],
      ['Firefox', [
        `On Android: tap the <b>⋮</b> menu, then <b>Install</b> (or <b>Add to Home screen</b>).`,
        `On a computer, Firefox can't install web apps — use Chrome or Edge for this one step.`
      ]]
    ];
    panel(`
      <h1>Put AraBuzz on the home screen</h1>
      <p class="lead">One tap to open, a proper app icon, and the device keeps its saved
         words safe. Do this on the device your kid will actually use.</p>
      ${canPrompt ? `
        <button class="btn-primary btn-wide" id="obInstallNow" data-label="Install AraBuzz on this device">
          Install AraBuzz on this device</button>
        <p class="hint center-text">This browser can install it for you — one tap, done.
           The steps below are for other devices.</p>` : ''}
      ${B.map(([name, steps]) => `
        <details style="border-bottom:1px solid var(--line);padding:11px 0">
          <summary style="cursor:pointer;font-weight:600">${name}</summary>
          <ol class="ob-steps" style="margin-top:10px">${steps.map(t => `<li>${t}</li>`).join('')}</ol>
        </details>`).join('')}
      <p class="hint">Why it matters on an iPad: Safari can delete saved data for sites that
         only ever live in a browser tab. An installed AraBuzz is safe from that.</p>
      <button class="btn-quiet btn-wide" id="obBackBtn" style="margin-top:14px">← Back</button>`,
      { tag: 'Install the app' });

    if (canPrompt) $('#obInstallNow').onclick = async () => {
      const ev = window.ARABUZZ_INSTALL;
      if (!ev) return;
      try {
        ev.prompt();
        const r = await ev.userChoice;
        if (r && r.outcome === 'accepted') {
          window.ARABUZZ_INSTALL = null;
          window.U && U.toast && U.toast('Installed — look for the AraBuzz icon.', 'good');
        }
      } catch (e) { /* the written steps below still stand */ }
    };
    $('#obBackBtn').onclick = () => (backTo || handOver)();
  }

  /** The last screen a grown-up sees. Its whole job is the sentence about not
      helping — a first check that a parent has quietly corrected tells us
      nothing, and then every week after it is aimed at the wrong thing. */
  function handOver() {
    panel(`
      <div class="ob-tick">${window.Icon ? Icon.icon('sparkle', { size: 40, stroke: 1.4 }) : '★'}</div>
      <h1>Now hand it to your child</h1>
      <p class="lead">Ara — the macaw who runs the place — will ask their name, let them
         pick a badge, and then do a short spelling check: about twenty words, five
         minutes. It is not marked, and they cannot fail it.</p>

      <div class="ob-warn">
        <b>Please don’t help with the check.</b>
        <p>Not a hint, not a nudge, not “are you sure?”. It feels unkind for five minutes
           and it is the single most useful thing you can do.</p>
        <p>Everything AraBuzz does afterwards is built on what your child can spell
           <em>unaided today</em>. If the first check is a little better than the truth,
           every week that follows practises the wrong words — and they end up working
           harder for less. Let them get things wrong. That is the point of it.</p>
      </div>

      <p class="muted small">They will never see a score, a red mark, or a comparison
         with anyone else. And the moment the check finishes, your starting-point note
         is written — it will be waiting behind your PIN, under <b>Coach Report</b>.</p>

      <div class="ob-warn" style="border-color:var(--honey)">
        <b>One thing worth doing first: install AraBuzz on the kid\u2019s device.</b>
        <p>It becomes a real app icon — one tap to open every time, no address to type,
           and the device keeps its saved words safe.
           <a href="#" id="obInstallHow"><b>How to install it \u2192</b></a></p>
      </div>

      <button class="btn-primary btn-wide" id="obGo" data-label="I’ve handed it over">
        I’ve handed it over</button>
      <button class="btn-quiet btn-wide" id="obBackBtn" style="margin-top:10px">← Back</button>`,
      { tag: 'Over to them' });

    $('#obGo').onclick = () => finish();
    $('#obBackBtn').onclick = () => askDevice();
    $('#obInstallHow').onclick = (e) => { e.preventDefault(); installGuide(handOver); };
  }

  function finish() {
    if (location.search) history.replaceState({}, '', location.pathname);
    sessionStorage.removeItem('arabuzz.joining');
    close();
    if (w.UI && UI.afterOnboard) UI.afterOnboard(Cloud.whoAmI());
  }

  /* ==========================================================================
     7 · Signing in when you are already a member
     Two doors, deliberately unequal in size. Parents get the big warm one —
     email, code, done. The admin door is a quiet line at the bottom with a
     password behind it, because Prem asked for his sign-in to be nothing like
     a parent's: knowing an email address must never be enough to reach the
     console that sees every family.
     ========================================================================== */
  function askSignIn() {
    panel(`
      <h1>Welcome</h1>
      <p class="lead">Already registered? Enter your email and we’ll send you a sign-in
         code. No password to remember.</p>
      <div class="field"><label for="obEmail">Email</label>
        <input id="obEmail" type="email" inputmode="email" autocomplete="email"
               placeholder="you@example.com"></div>
      <div id="obErr" class="feedback bad" style="display:none"></div>
      <button class="btn-primary btn-wide" id="obGo" data-label="Email me a code">Email me a code</button>
      <p class="hint center-text">Not part of AraBuzz yet? It’s invitation-only — write to
         <a href="mailto:arabuzz@cokindlelabs.com">arabuzz@cokindlelabs.com</a> and ask to
         be added.</p>`,
      { tag: 'Sign in', foot: '<a href="#" id="obAdmin" style="color:inherit">Admin sign in</a>' });

    const go = $('#obGo');
    const send = async () => {
      const email = $('#obEmail').value.trim();
      if (!/^\S+@\S+\.\S+$/.test(email)) return oops('That doesn’t look like an email address.');
      busy(go, true, 'Sending');
      try { await Cloud.sendLink(email, location.origin); askCode(email, askSignIn); }
      catch (e) { busy(go, false); oops(e.message || 'That didn’t send.'); }
    };
    go.onclick = send;
    $('#obEmail').onkeydown = e => { if (e.key === 'Enter') send(); };
    const adm = document.getElementById('obAdmin');
    if (adm) adm.onclick = (e) => { e.preventDefault(); askAdminSignIn(); };
  }

  /* ==========================================================================
     8 · The admin's door: email and password
     ========================================================================== */
  function askAdminSignIn() {
    panel(`
      <h1>Admin sign in</h1>
      <p class="muted">This door is for running AraBuzz — inviting families and
         publishing sheets. Parents don’t need it.</p>
      <div class="field"><label for="obEmail">Email</label>
        <input id="obEmail" type="email" inputmode="email" autocomplete="username"
               placeholder="prem@cokindle.com"></div>
      <div class="field"><label for="obPwd">Password</label>
        <input id="obPwd" type="password" autocomplete="current-password" placeholder="••••••••"></div>
      <div id="obErr" class="feedback bad" style="display:none"></div>
      <button class="btn-primary btn-wide" id="obGo" data-label="Sign in">Sign in</button>
      <p class="hint center-text"><a href="#" id="obReset">Set or reset my password</a>
         &nbsp;·&nbsp; <a href="#" id="obBack">I’m a parent</a></p>`,
      { tag: 'Admin' });

    const go = $('#obGo');
    const attempt = async () => {
      const email = $('#obEmail').value.trim(), pwd = $('#obPwd').value;
      if (!/^\S+@\S+\.\S+$/.test(email)) return oops('That doesn’t look like an email address.');
      if (!pwd) return oops('Type your password — or use "Set or reset my password" below.');
      busy(go, true, 'Checking');
      try { await Cloud.signInPassword(email, pwd); route(); }
      catch (e) {
        busy(go, false);
        oops(/invalid/i.test(e.message || '') ? 'That email and password don’t match.'
          : (e.message || 'Could not sign in.'));
      }
    };
    go.onclick = attempt;
    $('#obPwd').onkeydown = e => { if (e.key === 'Enter') attempt(); };
    $('#obBack').onclick = (e) => { e.preventDefault(); askSignIn(); };
    $('#obReset').onclick = async (e) => {
      e.preventDefault();
      const email = $('#obEmail').value.trim();
      if (!/^\S+@\S+\.\S+$/.test(email)) return oops('Type your email first, then tap that again.');
      try {
        await Cloud.sendPasswordReset(email);
        panel(`
          <div class="ob-tick">${window.Icon ? Icon.icon('mail', { size: 40, stroke: 1.4 }) : '✉'}</div>
          <h1>Check your email</h1>
          <p class="lead">A link to choose a password has gone to <b>${esc(email)}</b>.
             Open it and you’ll land back here.</p>`, { tag: 'Admin' });
      } catch (err) { oops(err.message || 'Could not send that.'); }
    };
  }

  /** Arriving back from the set-password email. */
  function askNewPassword() {
    panel(`
      <h1>Choose a password</h1>
      <p class="muted">For the admin sign-in only. Parents never see or need this.</p>
      <div class="field"><label for="obPwd">New password</label>
        <input id="obPwd" type="password" autocomplete="new-password" placeholder="At least 8 characters"></div>
      <div class="field"><label for="obPwd2">Again, to be sure</label>
        <input id="obPwd2" type="password" autocomplete="new-password"></div>
      <div id="obErr" class="feedback bad" style="display:none"></div>
      <button class="btn-primary btn-wide" id="obGo" data-label="Save my password">Save my password</button>`,
      { tag: 'Admin' });

    $('#obGo').onclick = async () => {
      const a = $('#obPwd').value, b = $('#obPwd2').value;
      if (a.length < 8) return oops('Eight characters or more, please.');
      if (a !== b) return oops('Those two don’t match.');
      busy($('#obGo'), true);
      try {
        await Cloud.setPassword(a);
        window.U.toast('Password saved.', 'good');
        route();
      } catch (e) { busy($('#obGo'), false); oops(e.message || 'That didn’t save.'); }
    };
  }

  /* ==========================================================================
     The router: what does this person need next?
     ========================================================================== */
  function inviteCode() {
    const q = new URLSearchParams(location.search).get('join');
    return q || sessionStorage.getItem('arabuzz.joining') || null;
  }

  /** arabuzz.cokindlelabs.com/admin goes straight to the admin's door. */
  function onAdminPath() {
    return /^\/admin\/?$/.test(location.pathname);
  }

  async function route() {
    const code = inviteCode();

    // Back from a set-password email: that comes before everything else.
    if (Cloud.signedIn() && Cloud.inRecovery && Cloud.inRecovery()) return askNewPassword();

    if (!Cloud.signedIn()) {
      if (code) return showInvite(code);
      if (onAdminPath()) return askAdminSignIn();
      return askSignIn();
    }

    const me = Cloud.whoAmI() || await Cloud.load();

    /* An invitation belongs to the address it was sent to. If this browser is
       signed in as somebody ELSE — a leftover session, another family member,
       the admin's own account — say so plainly and offer the way out, instead
       of quietly building the family under the wrong account. The database
       refuses the mismatch too; this screen just makes it friendly. */
    if (code && (!me || !me.parent)) {
      try {
        const inv = await Cloud.peekInvite(code);
        const mine = String(Cloud.myEmail() || '').toLowerCase();
        const invited = String((inv && inv.email) || '').trim().toLowerCase();
        if (invited && mine && invited !== mine) {
          panel(`
            <h1>This invitation isn’t for this account</h1>
            <p class="lead">The invitation was sent to <b>${esc(inv.email)}</b>, but this
               browser is signed in as <b>${esc(Cloud.myEmail())}</b>.</p>
            <p class="muted small">Sign out, then open the invitation link again and sign in
               with <b>${esc(inv.email)}</b> — the code arrives in that inbox.</p>
            <button class="btn-primary btn-wide" id="obSwitch" data-label="Sign out and start over">
              Sign out and start over</button>
            <button class="btn-quiet btn-wide" id="obStay" style="margin-top:10px">← Back</button>`,
            { tag: 'Wrong account' });
          $('#obSwitch').onclick = async () => {
            try { await Cloud.signOut(); } catch (e) {}
            location.reload();      // the ?join code survives; sign-in starts clean
          };
          $('#obStay').onclick = () => {
            if (location.search) history.replaceState({}, '', location.pathname);
            sessionStorage.removeItem('arabuzz.joining');
            close();
            if (w.UI && UI.afterOnboard) UI.afterOnboard();
          };
          return;
        }
      } catch (e) { /* peek failed — the database check still guards the join */ }
    }

    if (!me || !me.parent) {
      // Nobody should type their details into something they haven't read.
      // The agreement is shown FIRST; the tick is remembered and recorded the
      // moment their account exists, a few seconds later.
      if (!sessionStorage.getItem('arabuzz.preagreed')) return askConsent(true);
      return askName(code);
    }
    if (!me.hasConsented)    return askConsent(false);
    if (!Cloud.pinIsSet())   return askPin();

    if (!me.isAdmin && !me.children.length) {
      // Which device, then the hand-over. The child is created on the next
      // screen, by the child, telling Ara their name.
      if (!localStorage.getItem('arabuzz.handedOver')) {
        localStorage.setItem('arabuzz.handedOver', '1');
        return askDevice();
      }
    }

    finish();
  }

  /** True when the app should stay out of the way until setup is finished. */
  function needed() {
    if (!Cloud.available()) return false;
    if (inviteCode()) return true;
    if (!Cloud.signedIn()) return true;
    if (Cloud.inRecovery && Cloud.inRecovery()) return true;
    const me = Cloud.whoAmI();
    if (!me) return true;
    if (!me.parent || !me.hasConsented || !Cloud.pinIsSet()) return true;
    return false;
  }

  w.Onboard = { route, needed, close, CONSENT, askSignIn, askAdminSignIn, askConsent, askPin,
                askDevice, handOver, installGuide, onAdminPath };
})(window);
